vim.o.breakindent = true
vim.o.clipboard = 'unnamedplus'
vim.o.completeopt = 'menuone,noselect'
vim.o.hlsearch = false
vim.o.ignorecase = true
vim.o.relativenumber = true
vim.o.mouse = 'a'
vim.o.smartcase = true
vim.o.termguicolors = true
vim.o.timeout = true
vim.o.timeoutlen = 300
vim.o.undofile = true
vim.o.updatetime = 250
vim.o.wrap = false
vim.wo.number = true
vim.wo.signcolumn = 'yes'
vim.o.cursorline = true
vim.o.lazyredraw = true
vim.o.incsearch = true
vim.o.scrolloff = 7
vim.o.splitbelow = true
vim.o.splitright = true
-- vim.o.shiftround = true
-- vim.o.showmatch = true
-- vim.o.smartindent = true
-- vim.o.smarttab = true
-- vim.o.tabstop = 4
-- vim.o.shiftwidth = 4
-- vim.o.softtabstop = 4
