export PATH=/usr/local/bin/code:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export GOPATH="$HOME/code/prod/gopath"
export MYPYPATH="$HOME//mypy_stubs"
PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="$PATH:$GOPATH/bin"

setopt SHARE_HISTORY
compinit -d $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION
zstyle ':completion:*' cache-path $XDG_CACHE_HOME/zsh/zcompcache